# Generated by Django 2.1.7 on 2019-03-03 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heavy_celery', '0002_auto_20170712_0625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='celerytasklog',
            name='task',
        ),
        migrations.RemoveField(
            model_name='workertasklog',
            name='worker',
        ),
        migrations.DeleteModel(
            name='CeleryTaskLog',
        ),
        migrations.DeleteModel(
            name='Worker',
        ),
        migrations.DeleteModel(
            name='WorkerTaskLog',
        ),
    ]
