# coding: utf-8
# Generated by Django 2.1.7 on 2019-03-03 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heavy_celery', '0003_auto_20190302_2256'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerHeartBeat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_id', models.CharField(blank=True, max_length=256, null=True, verbose_name='ワーカーID')),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='celerytask',
            name='worker_id',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='ワーカーID'),
        ),
    ]
