# Generated by Django 2.2.1 on 2019-05-17 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heavy_celery', '0004_auto_20190303_0128'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkerHeartBeat',
        ),
    ]
